project: wormWatcher
seed: 1337

paths:
  clips_dir: out/clips/D5W1P28Jun25
  out: out
  logs: logs
  events: events

# video & ROI
fps_override:          # optional
roi:
  apply: false
  erosion_px: 2

# segmentation
seg:
  bg_method: median
  bg_frames: 60
  threshold: otsu        # options: otsu | adaptive
  adaptive_block: 41      # odd int
  adaptive_C: 3
  keep_largest: true
  min_area: 1500
  max_area: 200000
  morph_open: 2
  morph_close: 4

# skeleton
skeleton:
  method: medial_axis    # medial_axis | thin
  spur_px: 6
  bridge_gaps_px: 2
  continuity_lambda: 0.5

# clitellum (width profile)
clitellum:
  search_range_pct: [0.25, 0.60]
  smooth_win: 9
  temporal_win: 7
  min_prominence_px: 2.5

# orientation
orientation:
  window_frames: 5
  flip_hysteresis: 3
  tip_curv_win: 5
  clitellum_bias: 0.2

# motion & freezing
motion:
  diff_thresh: 12
  freeze_motion_px: 250
  min_freeze_s: 0.5

# retraction detection
retract:
  min_dur_s: 0.5
  frac_body_len: 0.05

# events CSV schema (example)
events_csv: out/tables/D5W1P28Jun25_trials.csv
source_video: videos/D5W1P28Jun25.m4v
trial_id_col: 
clips_col: 
cs_frame_col: 
us_frame_col: 
roi_col:

id:
  prefix: T      # change to 'W' if you prefer
  digits: 3
  start: 1


# workers
workers: 3
