project: wormWatcher
seed: 1337

paths:
  clips_dir: out/clips/D5W1P28Jun25
  out_dir: out
  logs_dir: logs

video:
  fps_override: null            # set a number if metadata is wrong (e.g., 30.0)
  timestamps_from_ffprobe: false
  blur_ksize: 5
  thresh_method: otsu           # or 'adaptive'
  min_area_px: 50
  max_area_px: 50000
  erosion_iters: 1
  dilation_iters: 2
  rois:
    mode: rects
    rects:
      - id: worm_right          # your ROI
        x: 580
        y: 0
        w: 700
        h: 720

tracking:
  max_jump_px: 40
  smooth_window: 5
  interp_gaps: 2

features:
  px_per_mm: null               # set if calibrated
  freeze_speed_thresh_px_s: 6.0 # 0.2 px/frame @ 30 fps -> 6.0 px/s
  freeze_min_bout_s: 0.5        # 15 frames @ 30 fps -> 0.5 s

trials:
  lead_s: 1.0                   # 1 s baseline
  tone_s: 6.0                   # 6 s CS
  tail_s: 1.0                   # 1 s tail
  us_window_s: [5.0, 7.0]       # last 2 s of the CS window

qc:
  overlay_stride: 5
