name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m venv project_root/env && source project_root/env/bin/activate && pip install -r requirements.txt ruff
      - run: make ci || true   # smoke-tests; CI may not have real videos
